name: musicgnk
description: A simple application to play music from the user's downloads folder
publish_to: "none"

version: 1.2.0+3

environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_svg: ^2.0.7
    cupertino_icons: ^1.0.2
    permission_handler: ^11.1.0
    app_settings: ^5.1.1
    path_provider: ^2.0.5
    universal_platform: ^1.0.0+1
    audioplayers: ^5.2.1
    adaptive_theme: ^3.4.0
    window_manager: ^0.3.7
    file_picker: ^6.1.1
    flutter_riverpod: ^2.3.10
    url_launcher: ^6.2.2
    shared_preferences: ^2.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.13.1
    flutter_lints: ^3.0.1

flutter_launcher_icons: #Run "flutter pub run flutter_launcher_icons"
    #  image_path: "assets/Logo/icon-128x128.png"
    image_path_android: "assets/Logo/logoNoneTransparent.png"
    image_path_ios: "assets/Logo/logoNoneTransparent.png"
    android: true
    ios: true
    adaptive_icon_background: "assets/Logo/logoBackground.png" # only available for Android 8.0 devices and above
    adaptive_icon_foreground: "assets/Logo/logo.png" # only available for Android 8.0 devices and above
    remove_alpha_ios: true
    background_color_ios: "#ffffff"
    web:
        generate: true
        image_path: "assets/Logo/logo.png"
        background_color: "#152C3E00"
        theme_color: "#274B66"
    windows:
        generate: true
        image_path: "assets/Logo/logo.png"
        icon_size: 48 # min:48, max:256, default: 48
    macos:
        generate: true
        image_path: "assets/Logo/logo.png"

flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true
    assets:
        - assets/WebAudioFiles/Glossy.mp3
        - assets/WebAudioFiles/Titanium.mp3
        - assets/WebAudioFiles/Awaken.mp3
        - assets/WebAudioFiles/Chill.mp3
        - assets/WebAudioFiles/Space.mp3
        - assets/Logo/logo.png
        - assets/Logo/logoBackground.png
        - assets/Logo/logoNoneTransparent.png
    fonts:
        - family: Roboto
          fonts:
              - asset: assets/Fonts/Roboto-Regular.ttf
